In [1]:
import pandas as pd
import numpy as np
import xgboost as xgb

train_data = pd.read_csv('train.csv')
test_data = pd.read_csv('test.csv')

In [2]:
train_data

,id,squareMeters,numberOfRooms,hasYard,hasPool,floors,cityCode,cityPartRange,numPrevOwners,made,isNewBuilt,hasStormProtector,basement,attic,garage,hasStorageRoom,hasGuestRoom,price
0,0,34291,24,1,0,47,35693,2,1,2000,0,1,8,5196,369,0,3,3436795.2
1,1,95145,60,0,1,60,34773,1,4,2000,0,1,729,4496,277,0,6,9519958.0
2,2,92661,45,1,1,62,45457,4,8,2020,1,1,7473,8953,245,1,9,9276448.1
3,3,97184,99,0,0,59,15113,1,1,2000,0,1,6424,8522,256,1,9,9725732.2
4,4,61752,100,0,0,57,64245,8,4,2018,1,0,7151,2786,863,0,7,6181908.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22725,22725,55825,84,1,0,70,12031,3,10,2000,0,0,4477,786,345,0,0,5594137.1
22726,22726,65870,88,1,0,49,23197,9,9,2015,0,1,4811,2454,755,0,7,6594705.0
22727,22727,93192,42,1,0,39,8539,10,5,2014,1,0,5595,4072,789,0,0,9321511.4
22728,22728,65797,86,1,0,89,23197,2,10,2000,1,0,5358,2513,411,0,0,6584708.2
22729,22729,82244,18,1,0,38,86728,1,9,2018,1,0,6294,1291,572,0,6,8231424.8

In [3]:
test_data

,id,squareMeters,numberOfRooms,hasYard,hasPool,floors,cityCode,cityPartRange,numPrevOwners,made,isNewBuilt,hasStormProtector,basement,attic,garage,hasStorageRoom,hasGuestRoom
0,22730,47580,89,0,1,8,54830,5,3,1995,0,0,6885,8181,241,0,8
1,22731,62083,38,0,0,87,8576,10,3,1994,1,1,4601,9237,393,1,4
2,22732,90499,75,1,1,37,62454,9,6,1997,0,1,7454,2680,305,0,2
3,22733,16354,47,1,1,9,9262,6,5,2019,1,1,705,5097,122,1,5
4,22734,67510,8,0,0,55,24112,3,7,2014,1,1,3715,7979,401,1,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15149,37879,86184,74,1,1,73,14009,2,10,1993,1,0,3714,3894,665,1,1
15150,37880,45885,41,1,1,64,84208,4,5,2008,0,0,783,7628,976,0,0
15151,37881,73554,51,0,0,41,49263,10,5,2004,0,1,8207,1777,775,0,10
15152,37882,77604,51,0,1,33,67056,4,3,2019,0,0,9578,9706,135,0,2
15153,37883,18179,50,1,0,41,50124,2,2,2004,1,0,4163,9923,622,0,6

In [4]:
train_data.info()
train_data.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22730 entries, 0 to 22729
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 22730 non-null  int64
 1   squareMeters       22730 non-null  int64
 2   numberOfRooms      22730 non-null  int64
 3   hasYard            22730 non-null  int64
 4   hasPool            22730 non-null  int64
 5   floors             22730 non-null  int64
 6   cityCode           22730 non-null  int64
 7   cityPartRange      22730 non-null  int64
 8   numPrevOwners      22730 non-null  int64
 9   made               22730 non-null  int64
 10  isNewBuilt         22730 non-null  int64
 11  hasStormProtector  22730 non-null  int64
 12  basement           22730 non-null  int64
 13  attic              22730 non-null  int64
 14  garage             22730 non-null  int64
 15  hasStorageRoom     22730 non-null  int64
 16  hasGuestRoom       22730 non-null  int64
 17  price              22730 non-null  float64
dtypes: float64(1), int64(17)
memory usage: 3.1 MB

id                   0
squareMeters         0
numberOfRooms        0
hasYard              0
hasPool              0
floors               0
cityCode             0
cityPartRange        0
numPrevOwners        0
made                 0
isNewBuilt           0
hasStormProtector    0
basement             0
attic                0
garage               0
hasStorageRoom       0
hasGuestRoom         0
price                0
dtype: int64

In [5]:
test_data.info()
test_data.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15154 entries, 0 to 15153
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 15154 non-null  int64
 1   squareMeters       15154 non-null  int64
 2   numberOfRooms      15154 non-null  int64
 3   hasYard            15154 non-null  int64
 4   hasPool            15154 non-null  int64
 5   floors             15154 non-null  int64
 6   cityCode           15154 non-null  int64
 7   cityPartRange      15154 non-null  int64
 8   numPrevOwners      15154 non-null  int64
 9   made               15154 non-null  int64
 10  isNewBuilt         15154 non-null  int64
 11  hasStormProtector  15154 non-null  int64
 12  basement           15154 non-null  int64
 13  attic              15154 non-null  int64
 14  garage             15154 non-null  int64
 15  hasStorageRoom     15154 non-null  int64
 16  hasGuestRoom       15154 non-null  int64
dtypes: int64(17)
memory usage: 2.0 MB

id                   0
squareMeters         0
numberOfRooms        0
hasYard              0
hasPool              0
floors               0
cityCode             0
cityPartRange        0
numPrevOwners        0
made                 0
isNewBuilt           0
hasStormProtector    0
basement             0
attic                0
garage               0
hasStorageRoom       0
hasGuestRoom         0
dtype: int64

In [6]:
X_train = train_data.drop(columns=['price'])
y_train = train_data['price']
X_test = test_data

In [7]:
from sklearn.feature_selection import RFE
from xgboost import XGBRegressor

In [8]:
model = XGBRegressor(objective='reg:squarederror', n_estimators=100, max_depth=5, learning_rate=0.05)

rfe = RFE(estimator=model, n_features_to_select=10, step=1)

rfe.fit(X_train, y_train)

RFE(estimator=XGBRegressor(base_score=None, booster=None, callbacks=None,
                           colsample_bylevel=None, colsample_bynode=None,
                           colsample_bytree=None, device=None,
                           early_stopping_rounds=None, enable_categorical=False,
                           eval_metric=None, feature_types=None, gamma=None,
                           grow_policy=None, importance_type=None,
                           interaction_constraints=None, learning_rate=0.05,
                           max_bin=None, max_cat_threshold=None,
                           max_cat_to_onehot=None, max_delta_step=None,
                           max_depth=5, max_leaves=None, min_child_weight=None,
                           missing=nan, monotone_constraints=None,
                           multi_strategy=None, n_estimators=100, n_jobs=None,
                           num_parallel_tree=None, random_state=None, ...),
    n_features_to_select=10)

In [9]:
selected_features = X_train.columns[rfe.support_]
print("Selected features:", selected_features.tolist())

feature_ranking = pd.DataFrame({
    'Feature': X_train.columns,
    'Ranking': rfe.ranking_
}).sort_values(by='Ranking')
print(feature_ranking)

Selected features: ['squareMeters', 'numberOfRooms', 'floors', 'cityCode', 'cityPartRange', 'numPrevOwners', 'made', 'basement', 'attic', 'garage']
              Feature  Ranking
8       numPrevOwners        1
1        squareMeters        1
2       numberOfRooms        1
14             garage        1
13              attic        1
5              floors        1
6            cityCode        1
7       cityPartRange        1
12           basement        1
9                made        1
16       hasGuestRoom        2
0                  id        3
10         isNewBuilt        4
4             hasPool        5
11  hasStormProtector        6
3             hasYard        7
15     hasStorageRoom        8

In [10]:
X_train = train_data.drop(columns=['price', 'hasGuestRoom', 'id', 'isNewBuilt', 'hasPool', 'hasStormProtector', 'hasYard', 'hasStorageRoom'])
y_train = train_data['price']
X_test = test_data.drop(columns=['hasGuestRoom', 'id', 'isNewBuilt', 'hasPool', 'hasStormProtector', 'hasYard', 'hasStorageRoom'])

In [11]:
model = XGBRegressor(objective='reg:squarederror', eval_metric='rmsle', n_estimators=1000, learning_rate=0.05)
model.fit(X_train, y_train)

predictions = model.predict(X_test)
X_test['PredictedPrice'] = predictions

print(X_test[['PredictedPrice']].head())

   PredictedPrice
0      4763992.50
1      6205575.50
2      9063184.00
3      1353110.75
4      6741477.50